import { defineConfig, globalIgnores } from 'eslint/config'
import nextVitals from 'eslint-config-next/core-web-vitals'
import nextTs from 'eslint-config-next/typescript'
import prettier from 'eslint-config-prettier'

// For more info, see https://github.com/storybookjs/eslint-plugin-storybook#configuration-flat-config-format
import storybook from "eslint-plugin-storybook";

// Based on nextjs guidance:
// https://nextjs.org/docs/app/api-reference/config/eslint
export default defineConfig([
  globalIgnores([
    "storybook-static", // Autogenerated from Storybook build.
    "public/uswds/**", // A vendor directory outside our control.
    "node_modules/**",
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  {
    files: ["**/*.{js,jsx,ts,tsx,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
    },
  },
  // Add Next.js specific rules
  ...nextVitals,
  ...nextTs,
  // Add Storybook specific rules for story files
  ...storybook.configs["flat/recommended"],
  // Disable ESLint rules that conflict with Prettier (should be last)
  prettier,
]);
