# Includes a11y testing.
name: Test Storybook

on:
  pull_request:
    paths:
      - "components/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
      - run: npm ci --timing
      - name: "Test Storybook"
        run: npm run test:storybook
